apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: s8g0572mn-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: s8g0572mn-python 
  name: s8g0572mn-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: s8g0572mn-python 
